# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df1029fe95aae0da9aee94127f9efb54dda3cb27209d84850a66df63c27bd258fb0cff4f809e7ae72bfd5e56f17c756d03f07ac059e080e61295377bcac1ea6c

test:
  secret_key_base: cfe2719daf1bc80abbf8f49ab0d83f9f7ae49fcf0acee47dc0a02f590730c239cda5b2233361acd3e0485bea53a3c7bec4fb9878df187d4964fe4edd6ac32adc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
